version: '3'

services:
    api:
        build: ./api
        tty: true
        volumes:
            - ./api:/api
        ports:
            - "0.0.0.0:8080:8080"
        links:
            - db

    db:
        build: ./db
        tty: true
        volumes:
            - ./db/init:/docker-entrypoint-initdb.d
            - ./db/data:/var/lib/mysql
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=PASSWORD
            - MYSQL_PASSWORD=password
