version: '3'

services:
    app:
        build: ./app
        tty: true
        volumes:
            - ./app:/app
        ports:
            - "0.0.0.0:3000:3000"

    api:
        build: ./api
        tty: true
        volumes:
            - ./api:/api
        ports:
            - "0.0.0.0:8080:8080"

    db:
        build: ./db
        tty: true
        volumes:
            - ./db/init:/docker-entrypoint-initdb.d
            - ./db/data:/var/lib/mysql
            - ./db/config:/etc/mysql/conf.d
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=PASSWORD
            - MYSQL_PASSWORD=password
